### ISSUE TITLE
Unhelpful error handling if `pkglist.d` files miss a package name behind an action (was: Does not work on Debian 11.0.0)

### ISSUE THREAD

**Issue by ChrisDate** [elmar/aptitude-robot#13]
Under the newly released version of Debian 11.0.0, aptitude-robot crashes with:

"Use of uninitialized value $pkg in hash element at /usr/sbin/aptitude-robot line 121."

**Comment by xtaran** [comment]
Hrm. Works fine for me. On Debian 11 as well as on Debian Unstable.

How complex is your config? The error message looks as if maybe a config file isn't syntactical as expected. Look for a lone dash, underscore or plus sign in a file under `/etc/aptitude-robot/pkglist.d/` which has no package name behind it. That's what I can imagine could cause such a warning on this line. Then again, I couldn't reproduce it that way.

So that might be an error handling issue. But that specific error message should be just a warning, not a fatal error. So the actual aborting might have happened elsewhere later.

Is there a chance that you can share your config? For now only files under `/etc/aptitude-robot/pkglist.d/` are of interest. It's also fine to send your config by e-mail privately if you don't want to post it here. (`man aptitude-robot` shows you both our e-mail addresses, Elmar's as well as mine, at the very end of the man page.)
